name: Build windows binary with Pyinstaller

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: stresstest-windows-executable
        path: src/dist/windows
